
----操作员表
CREATE TABLE T_SYS_AUT_OPERATOR
(
  OPERATOR_ID       VARCHAR2(10)  NOT NULL PRIMARY KEY,
  USERNAME          VARCHAR2(200),
  USERNAME_CN       VARCHAR2(200),
  USER_PASSWORD     VARCHAR2(255)
);
COMMENT ON TABLE T_SYS_AUT_OPERATOR IS '系统操作员表';
COMMENT ON COLUMN T_SYS_AUT_OPERATOR.OPERATOR_ID IS '操作员编号';
COMMENT ON COLUMN T_SYS_AUT_OPERATOR.USERNAME IS '用户名';
COMMENT ON COLUMN T_SYS_AUT_OPERATOR.USERNAME_CN IS '中文名';
COMMENT ON COLUMN T_SYS_AUT_OPERATOR.USER_PASSWORD IS '用户密码';

--系统权限资源表
CREATE TABLE T_SYS_ATU_PERMISSION (
  PERM_ID varchar2(10) NOT NULL PRIMARY KEY ,
  PERM_NAME varchar2(255),
  DESCRIPTION varchar2(255),
  RESOUCE varchar2(255),
  PARENT_ID varchar2(10)
);
 COMMENT ON TABLE  T_SYS_ATU_PERMISSION              IS '系统权限资源表';
 COMMENT ON COLUMN T_SYS_ATU_PERMISSION.PERM_ID      IS '权限编号';
 COMMENT ON COLUMN T_SYS_ATU_PERMISSION.PERM_NAME    IS '权限名字';
 COMMENT ON COLUMN T_SYS_ATU_PERMISSION.DESCRIPTION  IS '权限描述';
 COMMENT ON COLUMN T_SYS_ATU_PERMISSION.PARENT_ID    IS '父权限编号';
 COMMENT ON COLUMN T_SYS_ATU_PERMISSION.RESOUCE      IS '系统权限资源表';

--系统角色表
CREATE TABLE T_SYS_ATU_ROLE (
  ROLE_ID VARCHAR2(10) NOT NULL PRIMARY KEY,
  ROLE_NAME VARCHAR2(255),
  ROLE_DESC VARCHAR2(255)
);
COMMENT ON TABLE  T_SYS_ATU_ROLE                    IS '系统角色表';
COMMENT ON COLUMN T_SYS_ATU_ROLE.ROLE_ID            IS '角色编号';
COMMENT ON COLUMN T_SYS_ATU_ROLE.ROLE_NAME          IS '角色名称';
COMMENT ON COLUMN T_SYS_ATU_ROLE.ROLE_DESC          IS '角色描述';


---角色资源对应表
CREATE TABLE T_SYS_AUT_ROLE_PERMISSION (
  ROLE_ID       VARCHAR2(10) NOT NULL,
  PERMISSION_ID VARCHAR2(10) NOT NULL
);
COMMENT ON TABLE  T_SYS_AUT_ROLE_PERMISSION               IS '角色资源对应表';
COMMENT ON COLUMN T_SYS_AUT_ROLE_PERMISSION.ROLE_ID       IS '角色编号';
COMMENT ON COLUMN T_SYS_AUT_ROLE_PERMISSION.PERMISSION_ID IS '资源权限编号';

--权限资源对应表
CREATE TABLE T_SYS_AUT_USER_ROLE (
  OPERATOR_ID VARCHAR2(10),
  ROLE_ID     VARCHAR2(10)
);
COMMENT ON TABLE  T_SYS_AUT_USER_ROLE               IS '用户角色绑定表';
COMMENT ON COLUMN T_SYS_AUT_USER_ROLE.OPERATOR_ID   IS '用户编号';
COMMENT ON COLUMN T_SYS_AUT_USER_ROLE.ROLE_ID       IS '角色编号';

